petoteca/livros/urls.py
from django.urls import path

from . import views

app_name = 'livros'
urlpatterns = [

    path('', views.home, name="home-page"),

]

petoteca/login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.cadastroPage, name='cadastro'),
    path('logout/', views.logoutUser, name='logout'),
    path('ativar/<uidb64>/<token>', views.ativar, name='ativar'),
]

petoteca/petoteca/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('login/', include('login.urls')), 
    path('admin/', admin.site.urls),
    path('', include('livros.urls', namespace='livros')),
]

petoteca/livros/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    nome = models.CharField(max_length=30,null=True)
    descricao = models.TextField(null=True)

    class Meta:
        ordering = ['nome']

    def __str__(self) -> str:
        return self.nome

class Livro(models.Model):
    Disponivel = models.BooleanField(null=True)
    Titulo = models.CharField("Título", max_length = 100, null = True)
    Codigo = models.CharField("Código", max_length = 20, null = True)
    Autores = models.CharField(max_length = 100, null = True)
    Edicao = models.IntegerField("Edição", null = True, default=0)	
    Volume = models.IntegerField(null = True, default=0)
    state_choices = (
        ('Bem conservado','Bem conservado'),
        ('Conservado','Conservado'),
        ('Pouco conservado','Pouco conservado')
    )
    Estado = models.CharField(max_length = 30, choices = state_choices, null = True)
    type_choices = (
        ('Livro','Livro'),
        ('Cópia','Cópia')
    )
    Tipo = models.CharField(max_length = 30, choices = type_choices, default = 'Livro', null = True)
    Categoria = models.ForeignKey(Categoria, on_delete = models.SET_NULL,null=True)

    class Meta:
        ordering = ['Disponivel', 'Titulo','Autores']

    def __str__(self) -> str:
        return self.Titulo

class Emprestimo(models.Model):
    Livro = models.ForeignKey(Livro, on_delete = models.SET_NULL, null = True)
    Usuario = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    Nome = models.CharField("Nome do usuário", max_length = 100, null = True)
    Matricula = models.CharField("Matrícula do usuário", max_length = 20, null = True)
    Telefone = models.CharField("Telefone do usuário", max_length = 20, null = True)
    DataEmprestimo = models.DateField("Data do empréstimo", null = True)
    DataRecebimento = models.DateField("Data do recebimento estimado", null = True, )
    DataDevolucaoEstimado = models.DateField( "Data da devolução estimada", null = True)
    DataDevolucaoReal = models.DateField("Data da devolução real", null = True)
    Recebido = models.BooleanField(null = True, default = True)

petoteca/login/models.py
from django.db import models

petoteca/login/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
from django import forms 


class CreateUserForm(UserCreationForm): 
    def clean_email(self):
        data = self.cleaned_data['email']
        if data.split('@')[1] != "cear.ufpb.br":   
            raise forms.ValidationError("Necessário que o email seja do domínio @cear.")
        return data
    class Meta: 
        model = User
        fields = ['username', 'email', 'password1', 'password2']

petoteca/livros/views.py
from django.shortcuts import render
from .models import Livro, Categoria
from django.contrib.auth.decorators import login_required 
from django.db.models import Q
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives

@login_required(login_url='login:cadastro')
def home(request):
    q = request.GET.get('q1') if request.GET.get('q1') != None else ''
    pesquisa = True if request.GET.get('q1') != None and request.GET.get('q1') != '' else False
    livros = Livro.objects.filter(
        Q(Categoria__nome__icontains=q) |
        Q(Titulo__icontains=q) |
        Q(Autores__icontains=q)     
        )
    Categorias = Categoria.objects.all()
    livros_count = livros.count()
    categorias_count = Categorias.count()

    context = {'livros':livros, 'Categorias':Categorias, 'livros_count': livros_count, 'pesquisa':pesquisa, 'categorias_count': categorias_count}
    return render(request, 'livros/Home_page.html',context)

def enviar_email_emprestimo(nome_usuario, email_usuario, nome_livro, data_devolucao, data_limite):
    mail_subject = "Confirmação de empréstimo PEToteca"
    message = render_to_string("livros/Confirmação_Emprestimo.html", {
        "nome_do_usuario": nome_usuario,
        "nome_do_livro": nome_livro,
        "data_de_devolucao": data_devolucao,
        "data_limite_recebimento": data_limite
    })
    to_email = email_usuario
    email = EmailMultiAlternatives(mail_subject, message, to=[to_email])
    email.attach_alternative(message, "text/html")
    email.attach_file("livros\static\livros\Horário de Atendimento - Sala do PET 2022.png")
    email.send()

petoteca/login/views.py
from multiprocessing import context
from django.shortcuts import render, redirect 
from django.contrib.auth import authenticate, login, logout, get_user_model 
from django.contrib.auth.decorators import login_required 
from django.contrib import messages
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.core.mail import EmailMessage


from .forms import CreateUserForm 
from .tokens import account_activation_token


def logoutUser(request): 
    logout(request)
    return redirect('login:cadastro')

def cadastroPage(request): 
    if not request.user.is_authenticated: 
        form = CreateUserForm();  

        if request.method == 'POST':

            if request.POST.get('realSignUp'): 
                form = CreateUserForm(request.POST)
                if form.is_valid(): 
                    user = form.save(commit=False)
                    user.is_active = False 
                    user.save() 
                    activateEmail(request, user, form.cleaned_data.get('email'))
            elif request.POST.get('realSignIn'):
                username = request.POST.get('username')      
                password = request.POST.get('password')      
                user = authenticate(request, username=username, password=password)

                if user is not None: 
                    login(request, user)
                    return redirect('livros:home-page')
                else:
                    messages.info(request, 'Senha ou usuário incorretos')
    else: return redirect('livros:home-page')

    context = {'form': form}
    return render(request, 'login/cadastro.html', context)

def ativar(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()

        messages.success(request, f"Muito obrigado por confirmar seu email, {user.username}. Agora você pode acessar nosso acervo.")
    else:
        messages.error(request, "Link de ativação inválido!")

    return redirect('login:cadastro')

def activateEmail(request, user, to_email):
    mail_subject = "Ative sua conta"
    message = render_to_string("login/ativarconta.html", {
        'user': user.username,
        'domain': get_current_site(request).domain,
        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
        'token': account_activation_token.make_token(user),
        "protocol": 'https' if request.is_secure() else 'http'
    })
    email = EmailMessage(mail_subject, message, to=[to_email])
    if email.send():
        messages.success(request, f'Clique no email enviado para {to_email} e verifique sua conta.\nCaso não encontre, verifique a caixa de spam ou tente novamente.')
    else:
        messages.error(request, f'Problema ao enviar o email de verificação para {to_email}, veja se está digitado corretamente.')

petoteca/livros/templates/livros/Confirmação_Emprestimo.html
<html>
    <head>
        <style>
            h1 {
                text-align: center;
                font-size: 24px;
                font-weight: bold;
                color: #333;
                margin-bottom: 20px;
            }
            .container {
                width: 600px;
                margin: 0 auto;
                text-align: center;
                font-size: 18px;
                line-height: 1.5;
                color: #333;
            }
            .text-center {
                text-align: center;
                margin-bottom: 20px;
            }
            .bold {
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <h1>Confirmação de Empréstimo de Livro</h1>
        <div class="container">
            <p>Olá {{nome_do_usuario}},</p>
            <p>Confirmamos o seu empréstimo do livro 
                <span class="bold">{{nome_do_livro}}</span>, com a data limite de recebimento até 
                <span class="bold">{{data_limite_recebimento}}</span> e a data de devolução prevista para 
                <span class="bold">{{data_de_devolucao}}</span>. Por favor, lembre-se de que o livro deve ser recebido na sala do PET, 
                localizada no Prédio de Elétrica da UFPB. O Nosso horário de atendimento segue em anexo.</p>
            <p>Caso tenha alguma dúvida, não hesite em nos contatar pelo email pet.eletrica@cear.ufpb.br ou pelo instagram @peteletrica.</p>
            <p>Agradecemos pela preferência!</p>
            <p>Atenciosamente,</p>
            <p>Equipe PET Elétrica</p>
        </div>
    </body>
</html>

petoteca/login/templates/login/ativarconta.html
{% autoescape off %}
Olá, {{ user }}. Muito obrigado por se cadastrar no site da Petoteca. 

Para verificar sua conta, por favor clique no link disponibilizado abaixo: 

{{ protocol }}://{{ domain }}{% url 'login:ativar' uidb64=uid token=token %}
{% endautoescape %}

petoteca/login/templates/login/cadastro.html
<!DOCTYPE html>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
{% load static %}

<link rel="stylesheet" href="{% static 'login/style.css' %}">



<h2>Entre ou cadastre-se no site da PETOTECA</h2>

<div class="container" id="container">
	<div class="form-container sign-up-container">
		<form method="POST" action="">
      {% csrf_token %}
			<h1>Criar Conta</h1>
      {{form.username}}
      {{form.email}}
      {{form.password1}}
      {{form.password2}}	
			

			
			<!-- <br> -->
			<button name="realSignUp" value="1">Cadastrar-se</button>
		</form>
		
	</div>

	<div class="form-container sign-in-container">
		<form method="POST" action="">
			{% csrf_token %}
			<h1>Entrar</h1>
			<input type="username" name="username" placeholder="Usuário" /> 
			<input type="password" name="password" placeholder="Senha" />
			<a href="#">Esqueceu a senha?</a>
			<button name="realSignIn" value="1">Entrar</button>
		</form>
	</div>
	<div class="overlay-container">
		<div class="overlay">
			<div class="overlay-panel overlay-left">
				<h1>Bem-vindo de volta!</h1>
				<p>Para continuar acessando nosso acervo, insira seus dados pessoais</p>
				<button class="ghost" id="signIn">Entrar</button>
			</div>
			<div class="overlay-panel overlay-right">
				<h1>Olá, aluno!</h1>
				<p>Insira seus dados e tenha acesso ao acervo da biblioteca do PET-Elétrica UFPB</p>

				<button class="ghost" id="signUp">Cadastrar-se</button>
			</div>
		</div>
	</div>
</div>

<br>
{% if form.errors %}
	<div class="alert alert-danger" role="alert">
		{% for field in form %}
			{% for error in field.errors %}
						<span align = "justify" style="font-size:16px"> {{field.label}}: {{ error|escape }} </span> <br>
			{% endfor %}
		{% endfor %}
	{% endif %}
</div>

{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
    {{ message }}
  </div>
</div>
{% endfor %}

<script src="{% static 'login/script.js' %}"></script>